---
title: 'Day 12'
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Task description
Each row in the given file consist a character and a number. The characters are all lattitudes and directions, while the numbers represent the distance or angle that a ship is to move. The task is to find the manhattan distance of the final position, stating facing east.

## Task solution
```{r}
#Prepare input data
rm(list=ls())
file_name <- "input_file_12.txt"
input_file <- read_lines(file_name) 
```
```{r}
coords <- list(N = 0, E = 0, S = 0, W = 0)
directions <- c("N", "E", "S", "W")
#Number representation of list elements
direction <- 2

for (str in input_file) {
  to <- str %>% str_extract("[A-Z]")
  dist <- str %>% str_extract_all("[0-9]+") %>% as.numeric()

  if(to %in% c("F", "B")) {
    coords[[direction]] = coords[[direction]] + ifelse(to == "F", dist * 1, dist * -1)
  } else if (to %in% c("L", "R")) {
    rotations <- dist/90 * ifelse(to == "L", -1, 1)
    new_direction <- (direction + rotations) %% 4
    #Mod will mess upp if you can divide by 4
    direction <- ifelse(new_direction == 0, 4, new_direction)
  } else {
    coords[[to]] = coords[[to]] + dist
  }
}
coords

#Manhattan distance
abs(coords$N-coords$S) + abs(coords$E - coords$W)



```

