---
title: 'Day 7'
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Task description
We are given a file where each row describes what other bags a certain bag color contains. For example: light red bags contain 1 bright white bag, 2 muted yellow bags. We are to figure out which bags can contain shiny gold bags.

## Task solution
```{r}
#Prepare input data
file_name <- "input_file_7.txt"
input_file <- read_lines(file_name)
```
```{r}
#Checks what colors a bag contain
extract_content <- function(str) {
  str_arr <- str %>% str_split(" ", simplify = TRUE)
  color <- str_arr[1:2] %>% paste(collapse = " ")
  contains <- c()
  n_words <- length(str_arr)
  position <- 7

  #Since all strings follow the same structure, we can skip some words
  while(position < n_words) {
    contains <- c(contains, paste(str_arr[position - 1], str_arr[position], collapse = ""))
    position <- position + 4
  }
  list(color = color, contains = contains)
}

# a = input_file[2] %>% extract_content()
# a

#Checks what bags contain the colors passed in the find argument
filter <- function(find, to_search) {
  n <- to_search %>% length()
  to_filter <- c()
  filtered_colors <- c()
  
  for (i in 1:n) {
    checked <- extract_content(to_search[i])   
    matches <- (find %in% checked$contains) %>% sum()
    if(matches > 0) {
      filtered_colors <- c(filtered_colors, checked$color)   
      to_filter <- c(to_filter, i)
    }
  }
  
  list(filtered_colors = filtered_colors, to_filter = to_filter)
}

#filter(c("shiny gold"), input_file)

shiny_ways <- 0
look_for <- c("shiny gold")
filtered <- input_file
diff <- 0
while (TRUE) {
  result <- filter(look_for, filtered)
  colors <- result$filtered_colors
  indices <- result$to_filter
  
  diff <- indices %>% length
  look_for <- colors
  
  if (is.null(indices)) break
  
  filtered <- filtered[-indices] 
  shiny_ways <- shiny_ways + diff
}

shiny_ways
```



