---
title: 'Day 8'
output: github_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Task description
We are given a file where each row is a instruction. There are three types of instructions: acc, jmp and nop (add to count, jump to line and do nothing respectively). All are followed by an integer e.g. acc -1, nop 10, jmp -1 will subtract 1 from the count, do nothing, go back to nothing (and do the last two infinitely). Our task is to find out the final count. 

## Task solution
```{r}
#Prepare input data
file_name <- "input_file_8.txt"
input_file <- read_lines(file_name)
```
```{r}
read_instruction <- function(str) {
  split_str <- str %>% str_split(" ", simplify = TRUE)
  type <- split_str[1]
  number <- split_str[2]
  if (type == "nop") {
    list(index = 1, add = 0)
  } else if (type == "jmp") {
    list(index = as.numeric(number), add = 0) 
  } else if (type == "acc") {
    list(index = 1, add = as.numeric(number))
  }
}

visited <- c()
index <- 1
acc <- 0
#Run until you revisit an index
while (TRUE) {
  if (index %in% visited) break
  do <- read_instruction(input_file[index])
  visited <- c(visited, index) 
  index <- index + do$index
  acc <- acc + do$add 
}
acc
```



