---
title: 'Day 2'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Task description
We are given a [file](https://adventofcode.com/2020/day/2/input) whose rows contain an interval and a letter followed by a colon and a string. We need to parse the strings to count how many of them countain the letters according to the interval. E.g. `1-3 a: aaj` is accepted because it contains 2 of a, which is a number within 1-3. 

## Task solution
```{r}
#Prepare input data
input_file <- read_lines("input_file_2.txt")
```
```{r}
#Solving task
n_valid <- 0
index <- 0
for (row in input_file) {
  index <- index + 1
  
  parts <- str_split(row, " ", simplify = TRUE)
  
  interval <- str_split(parts[1], "-", simplify = TRUE) %>% 
    as.numeric() #Cast from string
  letter <- str_sub(parts[2], 1, 1)
  occurances <- str_count(parts[3], letter)
  
  if (interval[1] <= occurances) {
    if (occurances <= interval[2]) {
      n_valid <- n_valid + 1
    } 
  }
  
}

n_valid
```

